{
 "title": "Chronos Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Running Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "chronos_jobs_running" }
   ]
  },
  {
   "title": "Total Jobs Submitted",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chronos_jobs_submissions_total" }
   ]
  },
  {
   "title": "Average Job Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(chronos_jobs_duration_seconds_sum[5m]) / rate(chronos_jobs_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Total Job Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "chronos_jobs_retries_total" }
   ]
  }
 ]
}